#!/usr/local/cpanel/3rdparty/bin/perl

use Cpanel::Version ();
use Cpanel::Locale::Utils::3rdparty ();

if ( $Cpanel::Version::MAJORVERSION < 11.40 ) {
    print "This addon requires 11.40 or later.\n";
    exit(1);
}

mkdir( "/var/cpanel/apps", 0755 );

system '/usr/bin/rsync', '-rlptD', 'Cpanel/', '/usr/local/cpanel/Cpanel/';
system '/usr/bin/rsync', '-rlptD', 'base/', '/usr/local/cpanel/base/';
system '/usr/bin/rsync', '-rlptD', 'whostmgr/', '/usr/local/cpanel/whostmgr/';
install( "-o", "root", "-g", "wheel", "-m" . "0600", "icon/ico-twostepauth.jpg", "/usr/local/cpanel/whostmgr/docroot/addon_plugins/ico-twostepauth.jpg" );

print "Registering Locales\n";
system 'perl /usr/local/cpanel/base/3rdparty/twostepauth/add_lang_keys.pl >/dev/null 2>&1';
system '/usr/local/cpanel/bin/build_locale_databases >/dev/null';

print "Registering Plugin\n";
system '/usr/local/cpanel/bin/register_cpanelplugin /usr/local/cpanel/base/3rdparty/twostepauth/twostepauth.cpanelplugin';

print "Registering WHM Plugin\n";
system '/usr/local/cpanel/bin/register_appconfig base/3rdparty/twostepauth/addon_twostepauth.conf';

system '/scripts/restartsrv_cpsrvd';

exit(0);

sub install {
    system( "/usr/bin/install", @_ );
}

